config/routes.rb
Rails.application.routes.draw do
  get 'sub_genres/index'
  root 'application#hello'
  get 'auth/:provider/callback' => 'sessions#omniauth'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post 'watchlists/add_to_watchlist' => 'watchlists#add_to_watchlist'
  
  resources :user_movies
  resources :genres do
    resources :sub_genres
  end
  resources :users do
    resources :watchlists
    end
  resources :watchlists
  resources :movies do 
    resources :comments, only: [:index, :show]
  end
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :movies
    has_many :sub_genres
    
    validates :name, presence: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def new
        @genre=Genre.new
    end

    def index
        @genre = Genre.all
    end

    def create
        @genre = Genre.new(genre_params)
        if @genre.save
            redirect_to genres_path
        else
            render 'new'
        end
    end

    def show
        @genre = Genre.find_by(id: params[:id])
    end

    def edit
        @genre = Genre.find_by(id: params[:id])
    end

    def update
        @genre = Genre.find_by(id: params[:id])
        if @genre.update(genre_params)
            redirect_to genres_path
        else
            render 'edit'
        end
    end

private

    def genre_params
        params.require(:genre).permit(:name)
    end

end

app/helpers/genres_helper.rb
module GenresHelper


end

app/views/genres/edit.html.erb
<h2>Edit a Genre</h2>
<%= form_for @genre do |f| %>

<p><%= f.label :name %><br>
<%= f.text_field :name %></p>

<%= f.submit "Create genre" %>
    
<% end %>

app/views/genres/index.html.erb
<h1>List of Genres</h1>
<table class="table">
    <thead>
        <tr><th colspan="2"></th></tr>
    </thead>
    <tbody>
    <% @genre.each do |genre| %>
    <tr>
        <td>
    <%= genre.name %> </td><td><%= link_to "Edit", genre_path(genre), class: "button" %></td>
</tr>
    <% end %>
</tbody>
</table>  
<%= link_to "Add a new Genre", new_genre_path, class: "button" %>

app/views/genres/new.html.erb
<h2>Create a Genre</h2>
<%= form_for @genre do |f| %>

<p><%= f.label :name %><br>
<%= f.text_field :name %></p>

<%= f.submit "Create genre" %>
    
<% end %>

app/views/genres/show.html.erb
<h2>Genre Details</h2>

<h2><%= @genre.name %></h2>

<h3>Movies in this genre:</h3>
<ul>
    <% @genre.movies.each do |movie| %>
<li>
    <%= link_to movie.title, movie_path(movie) %>
</li>
<% end %>
</ul>

<%= link_to "Add a new Genre", new_genre_path %>