config/routes.rb
Rails.application.routes.draw do
  get 'sub_genres/index'
  root 'application#hello'
  get 'auth/:provider/callback' => 'sessions#omniauth'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post 'watchlists/add_to_watchlist' => 'watchlists#add_to_watchlist'
  
  resources :user_movies
  resources :genres do
    resources :sub_genres
  end
  resources :users do
    resources :watchlists
    end
  resources :watchlists
  resources :movies do 
    resources :comments, only: [:index, :show]
  end
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :comments
    has_many :watchlists
    # has_many :movies_on_watchlist, through: :watchlist, source: :movies
    has_many :movies, through: :comments
    
    validates :name, :email, presence: true
    validates :email, uniqueness: true

    def self.from_omniauth(auth)
        
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.name = auth['info']['name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(12)
            
            end
    end

    def watchlist_name=(name)
        self.watchlist = Watchlist.find_or_create_by(name: name)
      end
    
      def watchlist_name
         self.watchlist ? self.watchlist.name : nil
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]
    
    def new
        @user = User.new
    end

    def index
        if current_user
            @users = User.all
        else
            redirect_to '/'
        end
    end
    
    
    
    def show
        @user = User.find_by(id: params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit
        if current_user.admin
            @user = User.find_by(id: params[:id])
        else
            redirect_to '/'
        end
    end

    def update
        @user = User.find_by(id: params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end

    def destroy
        User.find(params[:id]).destroy
        redirect_to users_path
      end
private

    def user_params
        params.require(:user).permit(:name, :email, :password, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div id = "error explanation">
        <h3>There were some errors:</h3>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
        </ul>
    </div>
    <% end %>


<%= form_for @user do |f| %>
<div class="field<%=' field_with_errors' if @user.errors[:name].any? %>">
<p><%= f.label :name %><br>
<%= f.text_field :name %></p>
</div>

<div class="field<%=' field_with_errors' if @user.errors[:email].any? %>">
<p><%= f.label :email %><br>
<%= f.text_field :email %></p>
</div>  

<div class="field<%=' field_with_errors' if @user.errors[:password].any? %>">
<p><%= f.label :password %><br>
<%= f.password_field :password %></p>
</div>

<p><%= f.label :admin, 'Are you an admin?' %>
<%= f.check_box :admin %></p>

<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit User: <%= @user.name %></h2>
<%= render 'form' %>
    

app/views/users/index.html.erb
<h1><u>List of Users</u></h1>
<ul>
<% @users.each do |user| %>
<li>
    <%= user.name %>  <button> <%= link_to "Edit", edit_user_path(user) %> </button>  <button> <%= link_to "Delete", user, method: :delete, data: { confirm: "Confirm deletion?" } %></button>
</li>
<% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign up to join Cinophile!</h2>
<%= render "form" %>

app/views/users/show.html.erb
<%=flash[:success] %>

<h2>Hello, <%=@user.name %></h2>
 
Email: <%= @user.email %>
<br><br>

<button><%= link_to "List of Movies", movies_path %></button>

<% if logged_in? && current_user.admin %>
    <button><%= link_to "List of Users", users_path %></button>
<% end %>

<br><br>

<b>My Watchlists </b>
<button><%= link_to "Create New Watchlist", new_user_watchlist_path(:user_id) %></button>
<ul>
<% @user.watchlists.each do |watchlist| %>

<li><%= link_to watchlist.name, user_watchlist_path(@user, watchlist.id) %></li>
<% end %></ul>